(function(g){var window=this;'use strict';var V8=function(B){B.publish("cardstatechange",B.B7()&&B.TX()?1:0)},Q8=function(B,z){var T=g.B7(z),R=T?z:arguments;
for(T=T?0:1;T<R.length;T++){if(B==null)return;B=B[R[T]]}return B},tb7=function(B){var z=g.Pt(B);
B=g.Dk(B);return new g.Am(z.x,z.y,B.width,B.height)},jKF=function(B,z,T){var R=R===void 0?{}:R;
var h;return h=g.M4(B,z,function(){g.VO(h);T.apply(B,arguments)},R)},Ja=function(B){B=g.RR(B);
delete y8[B];g.Ep(y8)&&gD&&gD.stop()},ZFs=function(){gD||(gD=new g.Si(function(){Xtc()},20));
var B=gD;B.isActive()||B.start()},Xtc=function(){var B=g.YP();
g.uW(y8,function(z){e7U(z,B)});
g.Ep(y8)||ZFs()},p_=function(B,z,T,R){g.C2.call(this);
if(!Array.isArray(B)||!Array.isArray(z))throw Error("Start and end parameters must be arrays");if(B.length!=z.length)throw Error("Start and end points must be the same length");this.U=B;this.L=z;this.duration=T;this.V=R;this.coords=[];this.progress=this.X=0;this.W=null},e7U=function(B,z){z<B.startTime&&(B.endTime=z+B.endTime-B.startTime,B.startTime=z);
B.progress=(z-B.startTime)/(B.endTime-B.startTime);B.progress>1&&(B.progress=1);B.X=1E3/(z-B.W);B.W=z;sKI(B,B.progress);B.progress==1?(B.T=0,Ja(B),B.onFinish(),B.lr()):B.isPlaying()&&B.qe()},sKI=function(B,z){typeof B.V==="function"&&(z=B.V(z));
B.coords=Array(B.U.length);for(var T=0;T<B.U.length;T++)B.coords[T]=(B.L[T]-B.U[T])*z+B.U[T]},E6I=function(B,z){g.s3.call(this,B);
this.coords=z.coords;this.x=z.coords[0];this.y=z.coords[1];this.z=z.coords[2];this.duration=z.duration;this.progress=z.progress;this.fps=z.X;this.state=z.T},$4=function(B,z,T,R,h){p_.call(this,z,T,R,h);
this.element=B},S9U=function(B,z,T,R,h){if(z.length!=2||T.length!=2)throw Error("Start and end points must be 2D");
$4.call(this,B,z,T,R,h)},BYg=function(B){return Math.pow(B,3)},zuW=function(B){return 3*B*B-2*B*B*B},TYI=function(B){g.K.call(this);
this.U=B||window;this.T=[]},Pv=function(B){return B.baseUrl||null},x4=function(B,z){return g.v6(g.s9(B,z),function(T){return!!T})},Rus=function(B,z,T){function R(hK){var zP=hK.hovercardButton;
if(!zP)return null;zP=zP.subscribeButtonRenderer;if(!zP)return null;var ld=W(zP.unsubscribedButtonText),t=W(zP.subscribedButtonText);if(zP.subscribed){var UH=W(zP.subscriberCountWithUnsubscribeText);var Qz=W(zP.subscriberCountText)}else UH=W(zP.subscriberCountText),Qz=W(zP.subscriberCountWithSubscribeText);var vb=null;if(hK.signinEndpoint){vb=Q8(hK,"signinEndpoint","webNavigationEndpointData","url");if(!vb){var AI,lW;vb=(lW=g.u((AI=zP.signInEndpoint)==null?void 0:AI.commandMetadata,g.Gw))==null?void 0:
lW.url}if(!vb)return null}return ld&&(t||vb)?{subscribed:zP.subscribed,subscribeText:ld,subscribeCount:UH,unsubscribeText:t,unsubscribeCount:Qz,enabled:zP.enabled,signinUrl:vb,classic:hK.useClassicSubscribeButton}:null}
function h(hK){if(hK){var zP=[],ld=hK.videoId;ld&&zP.push("v="+ld);(ld=hK.playlistId)&&zP.push("list="+ld);(hK=hK.startTimeSeconds)&&zP.push("t="+hK);return"/watch?"+zP.join("&")}}
function W(hK){if(!hK)return null;var zP=hK.simpleText;return zP?zP:hK.runs?g.s9(hK.runs,function(ld){return ld.text}).join(""):null}
z=z.endscreenElementRenderer;if(!z)return null;var b=z.style,l=z.endpoint||{},w=null,q=null,c=!1,L=null,C=null,r=null,F=null,A=!1,a=null,V=null,M=null,x=null,v=null,n=null;if(b==="VIDEO")g.u(l,g.fl)?w=g.u(l,g.fl).url:(n=g.u(l,g.E2),w=h(n)),q=!1,L=B,z.thumbnailOverlays?(c=z.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,C=W(c.text),c=c.style==="LIVE"):C=W(z.videoDuration);else if(b==="PLAYLIST")g.u(l,g.fl)?w=g.u(l,g.fl).url:(n=g.u(l,g.E2),w=h(n)),q=!1,L=B,r=W(z.playlistLength);else if(b===
"CHANNEL"){if(A=Q8(l,"browseEndpoint","browseId"))F=A,w="/channel/"+F;q=!1;L="new";(A=!!z.isSubscribe)?a=R(z):V=W(z.subscribersText)}else b==="WEBSITE"?((M=Q8(l,"urlEndpoint","url"))&&(w=M),q=!0,L="new",M=z.icon.thumbnails[0].url):b==="CREATOR_MERCHANDISE"&&(z.productPrice&&(x=W(z.productPrice)),z.additionalFeesText&&(v=W(z.additionalFeesText)),(q=Q8(l,"urlEndpoint","url"))&&(w=q),q=!0,L="new");B=Q8(z,"title","accessibility","accessibilityData","label");var Z=z.endpoint?z.endpoint.clickTrackingParams:
null,N="";if(z.metadata){var TP=W(z.metadata);TP&&(N=TP)}return{id:"element-"+T,type:b,title:W(z.title),metadata:N,callToAction:W(z.callToAction),AL:z.image,iconUrl:M,left:Number(z.left),width:Number(z.width),top:Number(z.top),aspectRatio:Number(z.aspectRatio),startMs:Math.floor(Number(z.startMs)),endMs:Math.floor(Number(z.endMs)),videoDuration:C,Rw:c,playlistLength:r,channelId:F,subscribeButton:a,subscribersText:V,isSubscribe:A,targetUrl:w||null,uJ:q,sessionData:Z?{itct:Z}:null,CfJ:L,rC:B?B:null,
isPlaceholder:z.isPlaceholder,impressionUrls:x4(z.impressionUrls||[],Pv),Ly:x4(z.hovercardShowUrls||[],Pv),clickUrls:x4(l.loggingUrls||[],Pv),visualElement:g.Vl(z.trackingParams),productPrice:x,additionalFeesText:v,watchEndpoint:n||null}},hup=function(B,z){var T={startMs:Math.floor(Number(B.startMs)),
impressionUrls:x4(B.impressionUrls||[],Pv),elements:x4(B.elements||[],function(R,h){return Rus(z,R,h)})};
B.trackingParams&&(T.visualElement=g.Vl(B.trackingParams));return T},Wu7=function(B){g.I$.call(this,B);
this.W=this.endscreen=null;this.U={};this.X={};this.V=this.Y=null;this.J=[];this.T=null;this.TZ=!0;this.L=0;B=B.K();this.N=g.xC(B)||g.Df(B);this.events=new g.kb(this);g.m(this,this.events);this.events.Z(this.player,g.YQ("creatorendscreen"),this.onCueRangeEnter);this.events.Z(this.player,g.lu("creatorendscreen"),this.onCueRangeExit);this.events.Z(this.player,"resize",this.ox);this.events.Z(window,"focus",this.utd);this.load();var z=g.ES("STYLE");(g.fr("HEAD")[0]||document.body).appendChild(z);this.addOnDisposeCallback(function(){g.RK(z)});
z.sheet&&(z.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),z.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},b9P=function(B){return B.player.getVideoData().Jj?"current":B.N?"new":"current"},vv=function(B){return B.player.K().playerStyle==="creator-endscreen-editor"},Y57=function(B){var z=B.player.getVideoData(),T=z.videoId;
B.W&&B.W.abort();T={method:"POST",onFinish:function(h){var W=B.W=null;h.status===200&&(h=h.responseText,h.substring(0,3)===")]}"&&(h=h.substring(3),W=JSON.parse(h),W=hup(W,b9P(B))));DK(B,W)},
urlParams:{v:T},withCredentials:!0};B.N&&(T.urlParams.ptype="embedded");var R=z.q_;R&&(T.postParams={ad_tracking:R});if(z=g.aSY(z))if(z=g.Xy(z),z=g.OB(z))B.W=g.yH(z,T)},DK=function(B,z,T){T=T===void 0?!0:T;
B.player.I7("creatorendscreen");B.Y&&(B.Y.dispose(),B.Y=null,B.V.dispose(),B.V=null);for(var R=g.d(Object.values(B.U)),h=R.next();!h.done;h=R.next())h.value.dispose();B.U={};B.X={};B.J.length>0&&(B.J.forEach(function(l){l.dispose()}),B.J.length=0);
B.T&&(g.iH(B.T,"ytp-ce-element-show"),B.T.setAttribute("aria-hidden","true"));B.L=0;if((B.endscreen=z)&&z.elements){T&&ltU(B);T=[];R=new g.Wj(z.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});T.push(R);B.player.K().U||(B.Y=new g.O({B:"div",G:"ytp-ce-shadow"}),g.Pw(B.player,B.Y.element,4),B.V=new g.Yp(B.Y,200));for(R=0;R<z.elements.length;++R){h=z.elements[R];var W=wlh(B,h);if(W){B.U[h.id]=W;B.X[h.id]=h;g.Pw(B.player,W.element,4);var b=new g.Wj(h.startMs,h.endMs,{id:"ytp-ce-element-"+
h.id,namespace:"creatorendscreen"});T.push(b);q5F(B,W,h)}else g.KV(new g.Z_("buildEndscreenElement null",h))}B.player.A$(T);B.ox()}},ltU=function(B){var z=g.yl(),T=g.gd();
T&&z&&B.endscreen.visualElement&&g.BP(g.Zb)(void 0,T,z,B.endscreen.visualElement)},wlh=function(B,z){var T=null;
switch(z.type){case "VIDEO":B={B:"div",nf:["ytp-ce-element","ytp-ce-video"],C:{tabindex:"0","aria-label":z.rC||"","aria-hidden":"true"},S:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",C:k4(z)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",C:{href:K_(B,z.targetUrl),tabindex:"-1"},S:[{B:"div",nf:["ytp-ce-video-title","ytp-webkit-ellipsis"],C:{dir:g.GE(z.title||"")},Yd:z.title},{B:"div",G:z.Rw?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Yd:z.videoDuration||void 0}]}]};T=new g.O(B);break;case "PLAYLIST":B={B:"div",nf:["ytp-ce-element","ytp-ce-playlist"],C:{tabindex:"0","aria-label":z.rC||"","aria-hidden":"true"},S:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",C:k4(z)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",C:{href:K_(B,z.targetUrl),tabindex:"-1"},S:[{B:"div",nf:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],C:{dir:g.GE(z.title||"")},Yd:z.title},{B:"div",G:"ytp-ce-playlist-count",
S:[{B:"div",G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",Yd:z.playlistLength||void 0}]}]}]};T=new g.O(B);break;case "CHANNEL":T={B:"div",nf:["ytp-ce-element","ytp-ce-channel",z.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],C:{tabindex:"0","aria-label":z.rC||"","aria-hidden":"true"},S:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",S:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
S:[{B:"div",G:"ytp-ce-expanding-overlay-body",S:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",S:[{B:"a",nf:["ytp-ce-channel-title","ytp-ce-link"],C:{href:K_(B,z.targetUrl),target:"_blank",tabindex:"-1",dir:g.GE(z.title||"")},Yd:z.title},z.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",S:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",z.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",Yd:z.subscribersText}:"",z.metadata?{B:"div",nf:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Yd:z.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",C:k4(z)}]};T=new g.O(T);var R=g.Nu(document,"div","ytp-ce-channel-subscribe",T.element)[0];if(z.subscribeButton&&z.channelId){g.ww(R,"ytp-ce-subscribe-button");if(B.player.K().U){var h=null;var W=z.sessionData.itct}else h="endscreen",W=null;h=new g.Ek(z.subscribeButton.subscribeText,z.subscribeButton.subscribeCount,z.subscribeButton.unsubscribeText,z.subscribeButton.unsubscribeCount,!!z.subscribeButton.enabled,!!z.subscribeButton.classic,
z.channelId,!!z.subscribeButton.subscribed,h,W,B.player,!1);R.appendChild(h.element);B.J.push(h)}break;case "WEBSITE":B={B:"div",nf:["ytp-ce-element","ytp-ce-website"],C:{tabindex:"0","aria-label":z.rC||"","aria-hidden":"true"},S:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",S:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",S:[{B:"div",G:"ytp-ce-expanding-overlay-body",S:[{B:"div",
G:"ytp-ce-expanding-overlay-body-padding",S:[{B:"div",G:"ytp-ce-website-title",C:{dir:g.GE(z.title||"")},Yd:z.title},{B:"div",G:"ytp-ce-website-metadata",Yd:z.metadata},{B:"a",nf:["ytp-ce-website-goto","ytp-ce-link"],C:{href:K_(B,z.targetUrl),target:"_blank",tabindex:"-1"},Yd:z.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",C:k4(z)},{B:"div",G:"ytp-ce-expanding-icon",C:i9W(z.iconUrl)}]};T=new g.O(B);break;case "CREATOR_MERCHANDISE":T="",z.productPrice&&(T={B:"div",G:"ytp-ce-merchandise-price-container",
S:[{B:"div",G:"ytp-ce-merchandise-price",Yd:z.productPrice}]},z.additionalFeesText&&T.S.push({B:"div",G:"ytp-ce-merchandise-additional-fees",Yd:z.additionalFeesText})),B={B:"div",nf:["ytp-ce-element","ytp-ce-merchandise"],C:{tabindex:"0","aria-label":z.rC||"","aria-hidden":"true"},S:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",S:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
S:[{B:"div",G:"ytp-ce-expanding-overlay-body",S:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",S:[{B:"div",G:"ytp-ce-merchandise-title",C:{dir:g.GE(z.title||"")},Yd:z.title},T,{B:"div",G:"ytp-ce-merchandise-metadata",Yd:z.metadata},{B:"a",nf:["ytp-ce-merchandise-goto","ytp-ce-link"],C:{href:K_(B,z.targetUrl),target:"_blank",tabindex:"-1"},Yd:z.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",C:k4(z)},{B:"div",G:"ytp-ce-merchandise-invideo-cta-container",S:[{B:"div",G:"ytp-ce-merchandise-invideo-cta",
Yd:z.callToAction||void 0}]}]},T=new g.O(B)}z.isPlaceholder&&g.ww(T.element,"ytp-ce-placeholder");return T},k4=function(B){if(B.AL)var z=B.AL.thumbnails;
return i9W(z?z[z.length-1].url:null)},i9W=function(B){return B?{style:"background-image: url("+B+")"}:{}},q5F=function(B,z,T){function R(w){w&&(z.listen("blur",function(){w.style.display!="none"&&B.TZ&&w.focus()}),z.Z(w,"focus",W),z.Z(w,"blur",b))}
function h(w){B.L+=w;B.L>0?(g.ww(z.element,"ytp-ce-force-expand"),mC(B,T.id,!0)):(g.iH(z.element,"ytp-ce-force-expand"),g.iH(z.element,"ytp-ce-element-hover"),mC(B,T.id,!1))}
function W(){h(1)}
function b(){h(-1)}
z.listen("mouseenter",function(){czW(B,z,T)});
z.listen("mouseleave",function(){LuF(B,z,T)});
B.player.K().U||z.listen("click",function(){g.ww(z.element,"ytp-ce-element-hover")});
z.listen("click",function(w){CTp(B,T,w)});
z.listen("keypress",function(w){CTp(B,T,w)});
z.listen("focus",function(){czW(B,z,T)});
z.listen("blur",function(){LuF(B,z,T)});
z.listen("touchstart",function(){czW(B,z,T)});
var l=g.t2("ytp-ce-expanding-overlay-hider",z.element);l&&z.Z(l,"touchstart",function(w){w.stopPropagation();g.iH(z.element,"ytp-ce-element-hover");g.iH(z.element,"ytp-ce-force-expand")});
z.listen("keydown",function(w){B.TZ=w.keyCode===9&&!w.shiftKey});
R(g.t2("ytp-sb-subscribe",z.element));R(g.t2("ytp-sb-unsubscribe",z.element));z.listen("focus",W);z.listen("blur",b)},CTp=function(B,z,T){if(z.targetUrl&&(!T||T.type!=="keypress"||T.keyCode===13)){for(var R=T.target;R&&!g.lH(R,"ytp-ce-element");){g.lH(R,"subscribe-label")&&rzp(B,z);
if(g.lH(R,"ytp-ce-channel-subscribe"))return;R=R.parentElement||null}if(!R||g.lH(R,"ytp-ce-element-hover")){T.preventDefault();T.stopPropagation();if(R=B.U[z.id])LuF(B,R,z),R.element.blur();if(T.ctrlKey||T.metaKey||z.CfJ==="new")rzp(B,z),B.player.sendVideoStatsEngageEvent(17,void 0),B.player.pauseVideo(),T=g.Xy(K_(B,z.targetUrl)),T=g.OB(T),g.Zw(T,void 0,z.sessionData);else{var h=g.Zf(B.player.K())||B.player.getVideoData().Jj,W=function(){var b=K_(B,z.targetUrl),l=z.sessionData,w=z.watchEndpoint,q=
g.bA(b);h&&q&&(q.v||q.list)?B.player.Dw(q.v,l,q.list,!1,void 0,w||void 0):g.Xo(b,l)};
rzp(B,z,function(){B.player.sendVideoStatsEngageEvent(17,W)})}}}},K_=function(B,z){B=B.player.K();
if(z){if(z.startsWith("//"))return B.protocol+":"+z;if(z.startsWith("/"))return g.Ti(B)+z}else return"";return z},czW=function(B,z,T){g.lH(z.element,"ytp-ce-element-hover")||(T.type==="VIDEO"||T.type==="PLAYLIST"?g.ww(z.element,"ytp-ce-element-hover"):B.player.K().U?(new g.Si(function(){g.ww(z.element,"ytp-ce-element-hover")},200)).start():g.ww(z.element,"ytp-ce-element-hover"),n_(B,T.Ly),mC(B,T.id,!0))},LuF=function(B,z,T){g.iH(z.element,"ytp-ce-element-hover");
g.iH(z.element,"ytp-ce-force-expand");mC(B,T.id,!1)},mC=function(B,z,T){B.Y&&(T?B.V.show():B.V.hide());
for(var R=g.d(Object.keys(B.U)),h=R.next();!h.done;h=R.next())h=h.value,h!==z&&g.L2(B.U[h].element,"ytp-ce-element-shadow-show",T)},n_=function(B,z,T){function R(){W||(h++,h===z.length&&(b.stop(),T&&T()))}
if(!z||z.length===0||vv(B))T&&T();else{z=onF(B,z);var h=0,W=!1,b=new g.Si(function(){W=!0;T&&T()},1E3,B);
b.start();for(B=0;B<z.length;B++)g.Hg(z[B],R)}},rzp=function(B,z,T){n_(B,z.clickUrls,T);
(B=g.gd())&&z.uJ&&g.iU(B,z.visualElement)},onF=function(B,z){var T=B.player.getVideoData().clientPlaybackNonce;
B=B.player.getCurrentTime().toFixed(2);T={CPN:T,AD_CPN:T,MT:B};B=[];for(var R=0;R<z.length;R++)B.push(Fuh(z[R],T));return B},Fuh=function(B,z){return B.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(T){var R=unescape(T);
R=R.substring(1,R.length-1);return z[R]?escape(z[R]):T})},Itg=function(B){return typeof B==="string"?B:""},uE=function(B,z,T){for(var R in z)if(z[R]===B)return B;
return T},Gsc=function(B,z,T,R){this.value=B;
this.target=z;this.showLinkIcon=T;this.T=R},Hv=function(B){return B.value?B.value:null},f_=function(B){if(!B)return null;
var z=g.Xy(Itg(B.value));z=g.OB(z);if(!z)return null;var T=uE(B.target,dJc,"current");if(T==null)B=null;else{var R=B.show_link_icon;B=new Gsc(z,T,R==="true"||R==="false"?R==="true":!0,B.pause_on_navigation!=null?B.pause_on_navigation:!0)}return B},AzK=function(B,z,T){this.type=B;
this.trigger=z;this.url=T},MV5=function(B){if(!B)return null;
var z=uE(B.type,ats),T=uE(B.trigger,UJg);B=B.url;B=Array.isArray(B)&&B.length?B[0]:B;B=f_(B?B:null);return z?new AzK(z,T,B):null},VV5=function(B,z,T,R,h){this.id=B;
this.type=z;this.style=T;this.data=h;this.action=R||[]},Qr5=function(B,z){return g.Cs(B.action,z)},yzU=function(B,z){this.context=B;
this.T=z},gn7=function(B){return B.customMessage?Ob("div","iv-card-message",B.customMessage):""},N6=function(B,z){B="background-image: url("+B+");";
var T=[];z&&T.push(z);return{B:"div",G:"iv-card-image",C:{style:B},S:T}},JzR=function(B){if(!B.metaInfo||B.metaInfo.length===0)return"";
var z=[];B=g.d(B.metaInfo);for(var T=B.next();!T.done;T=B.next())z.push(Ob("li","",T.value));return{B:"ul",G:"iv-card-meta-info",S:z}},Ob=function(B,z,T){z?typeof z==="string"?z={"class":z}:Array.isArray(z)&&(z={"class":z.join(" ")}):z={};
z.dir=g.GE(T);return{B:B,C:z,Yd:T}},plg=function(B){if(!B.customMessage)return"";
var z=["iv-card-action","iv-card-primary-link"],T={};B.u5&&(z.push("iv-card-action-icon"),T.style="background-image: url("+B.u5+");");T.dir=g.GE(B.customMessage);var R=[{B:"span",Yd:B.customMessage}];B.showLinkIcon&&(R.push("\u00a0"),R.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",nf:z,C:T,S:R}},ta=function(B,z,T,R){if(R){z=g.d(z);
for(var h=z.next();!h.done;h=z.next())B.T(h.value,R,T.id,T.sessionData,T.Bv.click,5)}},$JI=function(B,z){this.merchant=B;
this.price=z},PTW=function(B){var z;
(z=B)&&!(z=B.length>1?B.charAt(0)==="/"&&B.charAt(1)!=="/":B==="/")&&(z=B.replace(/^(https?:)?\/\//,"").split("/",1),z=!z||z.length<1||!z[0]?[]:z[0].toLowerCase().split(".").reverse(),z=z[0]==="com"&&z[1]==="youtube"||z[0]==="be"&&z[1]==="youtu");return z?B.indexOf("/redirect?")===-1:!1},xJU=function(B,z){return z?z:PTW(B)?"current":"new"},jO=function(B,z){g.K.call(this);
var T=this;this.element=B;this.context=z;this.EE=!1;this.Kf=new Map;this.sE=new Map;this.context.j.addEventListener(g.YQ("annotations_module"),function(R){(R=T.Kf.get(R))&&R.apply(T)});
this.context.j.addEventListener(g.lu("annotations_module"),function(R){(R=T.sE.get(R))&&R.apply(T)})},Xv=function(B,z,T,R,h,W,b){B.context.T.listen(z,"click",function(l){B.yq(T,R,h,W||[],b||0,l)});
B.context.T.listen(z,"touchstart",function(){B.EE=!1});
B.context.T.listen(z,"touchmove",function(){B.EE=!0})},vnh=function(B){var z;
return((z=g.u(B,g.fl))==null?0:z.url)?g.u(B,g.fl).url:(B=g.u(B,g.E2))&&B.videoId?(z="/watch?v="+B.videoId,B.playlistId&&(z+="&list="+B.playlistId),B.index&&(z+="&index="+B.index),B.startTimeSeconds&&(z+="&t="+B.startTimeSeconds),z):null},ZK=function(B,z,T){return{VP:(B.impressionLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""}),
click:(T.loggingUrls||[]).map(function(R){return R.baseUrl||""}),
close:(z.dismissLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""}),
xx:(z.impressionLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""}),
A2:(z.clickLoggingUrlsV2s||[]).map(function(R){return R.baseUrl||""})}},DJp=function(B,z,T){jO.call(this,z,T);
var R=this;this.j=B;this.eventId=null;this.O0=this.lO=this.Dm=this.Y=this.isInitialized=!1;this.cards=[];this.aK=this.J=this.zZ=this.V=this.IK=this.T=null;this.TZ=[];this.UE=this.L=this.Ef=this.XE=null;this.X=0;this.RK=new g.Si(function(){},T.dF.g2?4E3:3E3);
g.m(this,this.RK);this.eI=new g.Si(function(){});
g.m(this,this.eI);this.WD=new yzU(T,function(h,W,b,l,w,q){Xv(R,h,W,b,l,w,q)});
this.N=new g.O({B:"div",G:"iv-drawer",C:{id:"iv-drawer"},S:[{B:"div",G:"iv-drawer-header",C:{"aria-role":"heading"},S:[{B:"span",G:"iv-drawer-header-text"},{B:"button",nf:["iv-drawer-close-button","ytp-button"],C:{"aria-label":"Hide cards",tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});g.m(this,this.N);this.W=this.N.element;this.MG=new g.Yp(this.N,330);g.m(this,this.MG);this.U0=g.t2("iv-drawer-header-text",this.W);this.U=g.t2("iv-drawer-content",this.W);this.addCueRange(0,T.videoData.lengthSeconds*
1E3,"",function(){R.Dm&&eO(R,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(R.Dm=R.Y)&&sb(R)});
this.cD=new g.kb(this);g.m(this,this.cD);this.j.addEventListener("videodatachange",this.MK.bind(this))},ksg=function(B,z){z=z.data;
z.autoOpenMs&&B.addCueRange(z.autoOpenMs,0x8000000000000,"",function(){eO(B,"YOUTUBE_DRAWER_AUTO_OPEN")});
z.autoCloseMs&&B.addCueRange(z.autoCloseMs,0x8000000000000,"",function(){sb(B)});
var T=z.headerText;g.Wt(B.U0,T);B.J&&B.J.setAttribute("title",T);z.eventId&&(B.eventId=z.eventId);B.XE=g.Vl(z.trackingParams);B.L=g.Vl(z.closeTrackingParams);B.Ef=g.Vl(z.iconTrackingParams)},Kuq=function(B,z){var T=z.cardId?z.cardId:"cr:"+B.X,R=B.j.K().experiments.Cf("enable_error_corrections_infocard_web_client");
if(!z.content&&z.teaser.simpleCardTeaserRenderer&&R){var h=z.teaser.simpleCardTeaserRenderer,W=z.icon?z.icon.infoCardIconRenderer:null;if(h.channelAvatar&&h.channelAvatar.thumbnails&&h.channelAvatar.thumbnails.length>0)var b=Eb(h.channelAvatar.thumbnails,22,22).url;z={id:T,timestamp:B.X,type:"simple",teaserText:g.aU(h.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:{},sponsored:!1,Bv:{},Ys:null,hY:h.trackingParams?
g.Vl(h.trackingParams):null,Ef:W&&W.trackingParams?g.Vl(W.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,u5:null,title:"",customMessage:"",url:null,onClickCommand:h.onTapCommand||null,mq:b};SO(B,z)}else{var l;if((l=z.content)==null?0:l.simpleCardContentRenderer){if(!z.cueRanges.length)return;b=(h=z.content)==null?void 0:h.simpleCardContentRenderer;h=z.teaser.simpleCardTeaserRenderer;W=z.icon?z.icon.infoCardIconRenderer:null;z={id:T,timestamp:B.X,type:"simple",teaserText:g.aU(h.message),
teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:BC(B,T,z,b),sponsored:!1,Bv:ZK(b,h,b.command),Ys:b.trackingParams?g.Vl(b.trackingParams):null,hY:h.trackingParams?g.Vl(h.trackingParams):null,Ef:W&&W.trackingParams?g.Vl(W.trackingParams):null,imageUrl:Eb(b.image.thumbnails,290,290).url,displayDomain:b.displayDomain?g.aU(b.displayDomain):null,showLinkIcon:!!b.showLinkIcon,u5:null,title:b.title?g.aU(b.title):"",
customMessage:b.callToAction?g.aU(b.callToAction):"",url:g.u(b.command,g.fl).url?f_({pause_on_navigation:!B.context.videoData.isLivePlayback,target:"new",value:g.u(b.command,g.fl).url}):null,onClickCommand:null};SO(B,z)}else{var w;if((w=z.content)==null?0:w.collaboratorInfoCardContentRenderer){if(!z.cueRanges.length)return;b=(W=z.content)==null?void 0:W.collaboratorInfoCardContentRenderer;h=z.teaser.simpleCardTeaserRenderer;W=z.icon?z.icon.infoCardIconRenderer:null;z={id:T,timestamp:B.X,type:"collaborator",
teaserText:g.aU(h.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:BC(B,T,z,b),sponsored:!1,Bv:ZK(b,h,b.endpoint),Ys:b.trackingParams?g.Vl(b.trackingParams):null,hY:h.trackingParams?g.Vl(h.trackingParams):null,Ef:W&&W.trackingParams?g.Vl(W.trackingParams):null,channelId:g.u(b.endpoint,g.UR).browseId,customMessage:b.customText?g.aU(b.customText):null,profileImageUrl:Eb(b.channelAvatar.thumbnails,290,
290).url,title:b.channelName?g.aU(b.channelName):"",metaInfo:[b.subscriberCountText?g.aU(b.subscriberCountText):""],url:f_({pause_on_navigation:!B.context.videoData.isLivePlayback,target:"new",value:g.u(b.endpoint,g.UR).canonicalBaseUrl?g.u(b.endpoint,g.UR).canonicalBaseUrl:"/channel/"+g.u(b.endpoint,g.UR).browseId}),onClickCommand:null};SO(B,z)}else{var q;if((q=z.content)==null?0:q.playlistInfoCardContentRenderer){if(!z.cueRanges.length)return;var c;b=(c=z.content)==null?void 0:c.playlistInfoCardContentRenderer;
h=z.teaser.simpleCardTeaserRenderer;W=z.icon?z.icon.infoCardIconRenderer:null;z={id:T,timestamp:B.X,type:"playlist",teaserText:g.aU(h.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:BC(B,T,z,b),sponsored:!1,Bv:ZK(b,h,b.action),Ys:b.trackingParams?g.Vl(b.trackingParams):null,hY:h.trackingParams?g.Vl(h.trackingParams):null,Ef:W&&W.trackingParams?g.Vl(W.trackingParams):null,Jp:Eb(b.playlistThumbnail.thumbnails,
258,290).url,customMessage:b.customMessage?g.aU(b.customMessage):null,playlistVideoCount:g.aU(b.playlistVideoCount),title:b.playlistTitle?g.aU(b.playlistTitle):"",metaInfo:[b.channelName?g.aU(b.channelName):"",b.videoCountText?g.aU(b.videoCountText):""],url:f_({pause_on_navigation:!B.context.videoData.isLivePlayback,target:"new",value:vnh(b.action)}),onClickCommand:null};SO(B,z)}else{var L;if((L=z.content)==null?0:L.videoInfoCardContentRenderer){if(!z.cueRanges.length)return;var C;b=(C=z.content)==
null?void 0:C.videoInfoCardContentRenderer;h=z.teaser.simpleCardTeaserRenderer;W=z.icon?z.icon.infoCardIconRenderer:null;z={id:T,timestamp:B.X,type:"video",teaserText:g.aU(h.message),teaserDurationMs:Number(z.cueRanges[0].teaserDurationMs),startMs:Number(z.cueRanges[0].startCardActiveMs),autoOpen:!!z.autoOpen,sessionData:BC(B,T,z,b),sponsored:!1,Bv:ZK(b,h,b.action),Ys:b.trackingParams?g.Vl(b.trackingParams):null,hY:h.trackingParams?g.Vl(h.trackingParams):null,Ef:W&&W.trackingParams?g.Vl(W.trackingParams):
null,Jp:Eb(b.videoThumbnail.thumbnails,258,290).url,videoDuration:b.lengthString?g.aU(b.lengthString):null,customMessage:b.customMessage?g.aU(b.customMessage):null,title:b.videoTitle?g.aU(b.videoTitle):"",metaInfo:[b.channelName?g.aU(b.channelName):"",b.viewCountText?g.aU(b.viewCountText):""],isLiveNow:!!b.badge,url:f_({pause_on_navigation:!B.context.videoData.isLivePlayback,target:"new",value:vnh(b.action)}),onClickCommand:null};SO(B,z)}}}}}B.X++},Eb=function(B,z,T){for(var R=-1,h=-1,W=0;W<B.length;W++){if(B[W].height===
z||B[W].width===T)return B[W];
((B[W].height||0)<z||(B[W].width||0)<T)&&(R<0||(B[R].height||0)<(B[W].height||0)||(B[R].width||0)<(B[W].width||0))?R=W:((B[W].height||0)>=z||(B[W].width||0)>=T)&&(h<0||(B[h].height||0)>(B[W].height||0)||(B[h].width||0)>(B[W].width||0))&&(h=W)}return B[h>=0?h:R]},BC=function(B,z,T,R){return{feature:T.feature?T.feature:"cards",
src_vid:B.context.videoData.videoId,annotation_id:z,ei:B.context.videoData.eventId||"",itct:R.trackingParams||""}},nnF=function(B,z){if(z=mJU(B,z))z===B.T&&(B.T=null),B.j.removeCueRange(z.Hd.id),g.RK(z.S$),g.GU(B.cards,z),B.Ye(),zA(B)},eO=function(B,z,T){if(!B.Y){B.MG.show();
B.IK=new g.Si(function(){g.ww(B.context.j.getRootNode(),g.ZR.IV_DRAWER_OPEN)},0);
B.IK.start();B.cD.Z(B.U,"mousewheel",function(b){B.RK.start();b.preventDefault();b=b||window.event;var l=0;b.type=="MozMousePixelScroll"?l=0==(b.axis==b.HORIZONTAL_AXIS)?b.detail:0:window.opera?l=b.detail:l=b.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?b.wheelDeltaY/-30:b.wheelDeltaY/-1.2:b.wheelDelta/-1.6:b.wheelDeltaY/-3;if(b=l)B.U.scrollTop+=b});
B.Y=!0;var R=g.gd();R&&B.XE&&B.L&&g.w2(R,[B.XE,B.L]);z={TRIGGER_TYPE:z};for(var h=g.d(B.cards),W=h.next();!W.done;W=h.next())W=W.value,W.bG||(W.bG=!0,unc(B.context.logger,W.Hd.Bv.VP,z)),R&&g.w2(R,[W.Hd.Ys]);V8(B.j);T&&(B.V=new g.Si(function(){B.zZ=B.J;B.aK.focus()},330),B.V.start())}},sb=function(B){B.Y&&(B.MG.hide(),g.$K(B.cD),g.iH(B.context.j.getRootNode(),g.ZR.IV_DRAWER_OPEN),B.Y=!1,V8(B.j),B.V&&B.V.stop(),B.V=new g.Si(function(){B.zZ&&(B.zZ.focus(),B.zZ=null)},330),B.V.start())},H9R=function(B){g.qv(B.jk(),
[g.ZR.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.Pw(B.j,B.W,5);B.eA();B.J=g.t2("ytp-cards-button",B.j.getRootNode());B.aK=g.t2("iv-drawer-close-button",B.W);B.isInitialized=!0},ft7=function(B){B.TZ.push(g.Y2("iv-teaser-shown",B.YE,B));
B.TZ.push(g.Y2("iv-teaser-hidden",B.VIu,B));B.TZ.push(g.Y2("iv-teaser-clicked",B.OY,B));B.O0=!0},O9q=function(B,z){var T;
return z.onClickCommand&&((T=g.u(z.onClickCommand,g.dSs))==null?void 0:T.targetId)==="engagement-panel-error-corrections"?(B.UE=z,!0):!1},NYP=function(B,z){B.UE=z;
var T=B.j.getVideoData();if(!T)return!1;T=g.yB(T);if(T==null?0:T.markersMap)for(var R,h=0;((R=T)==null?void 0:R.markersMap.length)>h;h++){var W=void 0,b=(W=T)==null?void 0:W.markersMap[h];if(b.key==="ERROR_CORRECTION_MARKERS"&&(W=void 0,(b=(W=b.value)==null?void 0:W.markers)&&b.length>0))return R=void 0,z.startMs=((R=g.u(b[0],g.LCH))==null?void 0:R.timeRangeStartMillis)||0,B.UE=null,!0}return!1},SO=function(B,z){if(!O9q(B,z)||NYP(B,z)){var T=tVh(B,z);
if(T){var R={Hd:z,S$:T.element,bG:!1};if(z.onClickCommand)B.j.D("web_infocards_teaser_show_logging_fix")&&(B.O0||ft7(B),nnF(B,z.id),T=B.findLastIndex(R),g.yq(B.cards,T,0,R));else{B.isInitialized||H9R(B);nnF(B,z.id);var h=B.findLastIndex(R);g.yq(B.cards,h,0,R);T.Vu(B.U,h);B.Ye()}z.autoOpen?B.addCueRange(z.startMs,0x8000000000000,z.id,function(){B.Y||(B.T=R,zA(B),jrP(B,R),eO(B,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(T=B.context.j.getCurrentTime()*1E3,T<5E3&&T>z.startMs&&Xlp(B,R),B.addCueRange(z.startMs,
z.startMs+1,z.id,function(){Xlp(B,R)}),zA(B))}}},tVh=function(B,z){switch(z.type){case "simple":B=B.WD;
var T=z.displayDomain?{B:"div",G:"iv-card-image-text",Yd:z.displayDomain}:void 0;var R=plg(z);T={B:"div",nf:["iv-card"],S:[{B:"a",G:"iv-click-target",C:{href:z.url?Hv(z.url)||"":""},S:[N6(z.imageUrl,T),{B:"div",G:"iv-card-content",S:[Ob("h2",void 0,z.title),R]}]}]};T=new g.O(T);ta(B,g.OS("iv-click-target",T.element),z,z.url);z=T;break;case "collaborator":B=B.WD;T={B:"div",nf:["iv-card","iv-card-channel"],S:[{B:"a",nf:["iv-click-target"],C:{href:Hv(z.url)||"","data-ytid":z.channelId},S:[N6(z.profileImageUrl),
{B:"div",G:"iv-card-content",S:[gn7(z),{B:"h2",G:"iv-card-primary-link",Yd:z.title},JzR(z)]}]}]};T=new g.O(T);ta(B,g.OS("iv-click-target",T.element),z,z.url);z=T;break;case "playlist":B=B.WD;T={B:"div",nf:["iv-card","iv-card-playlist"],S:[{B:"a",G:"iv-click-target",C:{href:Hv(z.url)||""},S:[N6(z.Jp,{B:"div",G:"iv-card-image-overlay",S:[{B:"span",G:"iv-card-playlist-video-count",Yd:z.playlistVideoCount}]}),{B:"div",G:"iv-card-content",S:[gn7(z),Ob("h2","iv-card-primary-link",z.title),JzR(z)]}]}]};
T=new g.O(T);ta(B,g.OS("iv-click-target",T.element),z,z.url);z=T;break;case "productListing":B=B.WD;var h=z.offers.length!=0;T=["iv-card"];R="";var W=plg(z);h&&(T.push("iv-card-product-listing"),R="iv-card-primary-link",W=z.offers[0],h=[],W.price&&h.push({B:"div",G:"iv-card-offer-price",Yd:W.price}),W.merchant&&h.push({B:"div",G:"iv-card-offer-merchant",Yd:W.merchant}),W={B:"div",S:h});h=z.url?Hv(z.url)||"":"";T={B:"div",nf:T,C:{tabindex:"0"},S:[{B:"a",nf:["iv-card-image","iv-click-target"],C:{style:"background-image: url("+
z.imageUrl+");",href:h,"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",S:[z.sponsored?{B:"div",G:"iv-card-sponsored",S:["Sponsored",{B:"div",G:"iv-ad-info-container",S:[{B:"div",G:"iv-ad-info",Yd:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",S:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",C:{href:h},S:[Ob("h2",R,z.title),W]}]}]};T=new g.O(T);R=g.ES("span");g.Wt(R,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
T.oI(R,"adInfo");ta(B,g.OS("iv-click-target",T.element),z,z.url);z=T;break;case "video":B=B.WD;R=z.videoDuration?{B:"span",G:"iv-card-video-duration",Yd:z.videoDuration}:void 0;W=z.isLiveNow?{B:"span",nf:["yt-badge","yt-badge-live"],Yd:"LIVE NOW"}:null;h={B:"div",nf:["iv-card","iv-card-video"],S:[{B:"a",G:"iv-click-target",C:{href:((T=z.url)==null?void 0:Hv(T))||""},S:[N6(z.Jp,R),{B:"div",G:"iv-card-content",S:[gn7(z),Ob("h2","iv-card-primary-link",z.title),JzR(z),W]}]}]};T=new g.O(h);ta(B,g.OS("iv-click-target",
T.element),z,z.url);z=T;break;default:return null}return z},Z9K=function(B){if(B.T)return B.T.Hd.type==="productListing";
if(B.j.D("enable_wn_infocards")){var z;return!((z=B.cards)==null||!z.length)&&g.E9(B.cards,function(T){return T.Hd.type==="productListing"})}return g.E9(B.cards,function(T){return T.Hd.type==="productListing"})},zA=function(B){g.L2(B.j.getRootNode(),"ytp-cards-shopping-active",Z9K(B))},Xlp=function(B,z){if(!g.lH(B.j.getRootNode(),"ytp-cards-teaser-shown")){if(B.T!==z){var T=g.gd(),R=B.T?B.T.Hd.Ef:B.Ef;
T&&R&&g.qI(T,[R]);B.T=z;zA(B)}(T=B.isInitialized&&B.jk().style.display=="none")||(T=B.context.j.getPlayerState(),R=T===0&&B.context.j.getCurrentTime()===0,T=!(T===1||T===3||R));if(!T&&z.Hd.teaserDurationMs){var h;T={teaserText:z.Hd.teaserText,durationMs:z.Hd.teaserDurationMs,onClickCommand:z.Hd.onClickCommand,mq:(h=z.Hd.mq)!=null?h:null};B.j.Mb(!0,T)}B.eI.isActive()||((!B.Y||!B.RK.isActive()&&B.lO)&&jrP(B,z),B.eI.start(910+z.Hd.teaserDurationMs))}},jrP=function(B,z){B.N.vD?(z=new p_([0,
B.U.scrollTop],[0,z.S$.offsetTop],600,zuW),B.context.Y.listen(z,"animate",function(T){B.U.scrollTop=T.y}),B.context.Y.listen(z,"finish",function(T){B.U.scrollTop=T.y}),z.play()):(B.N.kW(!0),B.U.scrollTop=z.S$.offsetTop,B.N.kW(!1))},TA=function(B){return B.T&&B.T.Hd?B.T.Hd:B.cards[0]&&B.cards[0].Hd?B.cards[0].Hd:null},mJU=function(B,z){return g.Cs(B.cards,function(T){return T.Hd.id===z})},Rk=function(B,z,T){jO.call(this,B,z);
this.annotation=T;this.isActive=!1},euP=function(B){var z=B.annotation.data;
"start_ms"in z&&"end_ms"in z&&B.addCueRange(Number(z.start_ms),Number(z.end_ms),B.annotation.id,function(){B.show()},function(){B.hide()})},ht=function(B,z,T){Rk.call(this,B,z,T);
this.U=null;this.L=!1;this.Y=null;this.W=!1;this.T=this.X=this.V=null},srP=function(B,z){var T=T===void 0?0:T;
var R=tb7(z).width;g.pF(z,R);T=new S9U(z,[R,z.offsetTop],[R-R-T,z.offsetTop],200,BYg);g.m(B,T);B.context.Y.listen(T,"begin",function(){g.KF(z,!0)});
T.play()},BqF=function(B,z){if(z.channel_name){var T=B.createElement({B:"div",
nf:["iv-branding-context-name"],Yd:z.channel_name}),R=B.createElement({B:"div",nf:["iv-branding-context-subscribe"]}),h=z.standalone_subscribe_button_data;h&&(B.T=new g.Ek(h.subscribeText,h.subscribeCount,h.unsubscribeText,h.unsubscribeCount,!!h.enabled,!!h.classic,z.channel_id,!!h.subscribed,h.feature,z.session_data.itct,B.context.j,!1),B.T.Vu(R));var W=B.createElement({B:"div",nf:["iv-branding-context-subscribe-caret"]}),b=B.createElement({B:"div",nf:["branding-context-container-inner"]});b.appendChild(W);
b.appendChild(T);b.appendChild(R);g.KF(b,!1);var l=B.createElement({B:"div",nf:["branding-context-container-outer"]});l.appendChild(b);g.Ml(l,"right",z.image_width+"px");g.Bt(B.jk(),l);B.Y=new g.Si(function(){EnP(B,b,l)},500);
g.m(B,B.Y);B.context.T.listen(B.jk(),"mouseover",function(){S5P(B,b,l,W,z.image_height)});
B.context.T.listen(B.jk(),"mouseout",function(){B.Y.start()})}},S5P=function(B,z,T,R,h){B.Y.stop();
if(!B.W){var W=g.Dk(z);B.T||(z.style.width=g.Jm(W.width,!0),T.style.width=g.Jm(W.width,!0));g.Ml(R,"top",W.height-Math.max(Math.min(W.height,h)/2+10,20)+"px");g.Ml(R,"right","1px");B.W=!0;g.KF(z,!0);B.V=new g.Si(function(){g.ww(this.jk(),"iv-branding-active")},0,B);
B.V.start()}},EnP=function(B,z,T){g.iH(B.jk(),"iv-branding-active");
B.X=new g.Si(function(){g.KF(z,!1);B.T||(T.style.width=g.Jm(0,!0))},250);
B.X.start();B.W=!1},z5P=function(B,z,T,R,h,W,b){this.T=B;
this.Y=z;this.dF=T;this.videoData=R;this.logger=h;this.j=W;this.U=b},Tq7=function(B,z,T){Rk.call(this,B,z,T);
var R=this;this.J=this.isCollapsed=this.N=!1;this.X=5E3;this.U=this.Y=this.T=this.W=null;this.L=this.createElement({B:"div",nf:["iv-promo-contents"]});this.V=new g.Si(function(){R.T.setAttribute("aria-hidden","true");g.KF(R.Y,!1);g.KF(R.U,!0)},700,this);
g.m(this,this.V)},h5q=function(B){var z=B.annotation.data;
if(B.annotation.style==="cta")var T=6;else if(B.annotation.style==="video"||B.annotation.style==="playlist")T=7;B.X=z.collapsedelay_ms||B.X;var R=["iv-promo","iv-promo-inactive"];B.jk().setAttribute("aria-hidden","true");B.jk().setAttribute("aria-label","Promotion");B.jk().tabIndex=0;var h=B.annotation.Pu(),W=z.image_url;if(W){var b=B.createElement({B:"div",nf:["iv-promo-img","iv-click-target"]});W=B.createElement({B:"img",C:{src:W,"aria-hidden":"true"}});b.appendChild(W);z.video_duration&&!z.is_live?
(W=B.createElement({B:"span",G:"iv-promo-video-duration",Yd:z.video_duration}),b.appendChild(W)):z.playlist_length&&(W=B.createElement({B:"span",G:"iv-promo-playlist-length",Yd:z.playlist_length.toString()}),b.appendChild(W));h&&Xv(B,b,h,B.annotation.id,z.session_data,void 0,T)}h?(W=B.createElement({B:"a",G:"iv-promo-txt"}),g.ez(W,Hv(h)),B.T=W):B.T=B.createElement({B:"div",G:"iv-promo-txt"});switch(B.annotation.style){case "cta":case "website":var l=B.createElement({B:"p",S:[{B:"strong",Yd:z.text_line_1}]});
var w=B.createElement({B:"p",S:[{B:"span",G:"iv-promo-link",Yd:z.text_line_2}]});if(W=z.text_line_3){R.push("iv-promo-website-card-cta-redesign");var q=B.createElement({B:"button",nf:["iv-promo-round-expand-icon","ytp-button"]});W=B.createElement({B:"button",nf:["iv-button","iv-promo-button"],S:[{B:"span",G:"iv-button-content",Yd:W}]});var c=B.createElement({B:"div",G:"iv-promo-button-container"});c.appendChild(W);h&&Xv(B,B.jk(),h,B.annotation.id,z.session_data,void 0,T)}g.ww(B.T,"iv-click-target");
h&&Xv(B,B.T,h,B.annotation.id,z.session_data,void 0,T);break;case "playlist":case "video":l=B.createElement({B:"p",S:[{B:"span",Yd:z.text_line_1}]}),w=B.createElement({B:"p",S:[{B:"strong",Yd:z.text_line_2}]}),z.is_live&&(l=w,w=B.createElement({B:"span",nf:["yt-badge","iv-promo-badge-live"],Yd:"LIVE NOW"})),g.ww(B.T,"iv-click-target"),h&&Xv(B,B.T,h,B.annotation.id,z.session_data,void 0,T),R.push("iv-promo-video")}l&&B.T.appendChild(l);w&&B.T.appendChild(w);B.L.appendChild(B.T);c&&B.L.appendChild(c);
T=B.createElement({B:"div",G:"iv-promo-actions"});B.U=B.createElement({B:"button",nf:["iv-promo-expand","ytp-button"]});B.U.title="Expand";B.context.T.listen(B.U,"click",function(L){R5q(B,5E3,L)});
T.appendChild(B.U);g.KF(B.U,!1);B.context.T.listen(B.jk(),"mouseover",B.vz,B);B.context.T.listen(B.jk(),"mouseout",B.hc,B);B.context.T.listen(B.jk(),"touchend",function(L){R5q(B,5E3,L)});
B.Y=B.createElement({B:"button",nf:["iv-promo-close","ytp-button"]});B.Y.title="Close";B.context.T.listen(B.Y,"click",B.annotation.style==="cta"&&z.text_line_3?B.Et:B.Ac,B);T.appendChild(B.Y);g.qv(B.jk(),R);b&&(g.Bt(B.jk(),b),q&&b.appendChild(q));g.Bt(B.jk(),B.L);g.Bt(B.jk(),T)},R5q=function(B,z,T){T.stopPropagation();
Wbh(B);beF(B,z);B.T.focus()},YMW=function(B){B.isCollapsed||B.J||B.W||(g.ww(B.jk(),"iv-promo-collapsed"),B.isCollapsed=!0,B.V.start())},Wbh=function(B){B.V.stop();
B.isCollapsed&&(g.ci(B.jk(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),B.isCollapsed=!1,B.T&&B.T.removeAttribute("aria-hidden"),g.KF(B.U,!1),g.KF(B.Y,!0))},beF=function(B,z){B.W||(B.W=g.mW(function(){l05(this);
YMW(this)},z,B))},l05=function(B){B.W&&(g.XK.clearTimeout(B.W),B.W=null)},wDg=function(B){this.j=B},unc=function(B,z,T){z&&(T?WC(B,z.map(function(R){return g.Pu(R,T)})):WC(B,z))},WC=function(B,z,T,R){var h=1,W=void 0,b=-1;
if(T){var l=!1;W=function(){h--;h||l||(clearTimeout(b),l=!0,T())};
b=setTimeout(function(){l=!0;T()},1E3)}z=g.d(z||[]);
for(var w=z.next();!w.done;w=z.next())w=w.value,h++,g.Hg(w,W);R&&(h++,R!==0&&B.j.sendVideoStatsEngageEvent(R,W))},qMh=function(B){g.I$.call(this,B);
var z=this;this.TZ=this.J=!1;this.loadNumber=0;this.X={};this.logger=new wDg(this.player);this.W=new g.kb(this);this.V=this.L=null;this.events=new g.kb(this);this.R_=this.N=this.T=null;this.UE=[];g.m(this,this.W);this.W.Z(this.player,"onVideoAreaChange",function(){z.publish("onVideoAreaChange")});
this.W.Z(this.player,"onHideControls",function(){z.publish("onHideControls")});
this.W.Z(this.player,"onShowControls",function(){z.publish("onShowControls")});
this.W.Z(this.player,"resize",function(R){z.publish("resize",R)});
this.W.Z(this.player,"presentingplayerstatechange",function(R){z.publish("presentingplayerstatechange",R)});
this.subscribe("presentingplayerstatechange",this.gW,this);this.subscribe("resize",this.ze,this);this.player.K().lO.subscribe("vast_info_card_add",this.Pe,this);g.m(this,this.events);this.WD=this.createElement({B:"div",G:"video-custom-annotations"});this.U=new g.O({B:"div",nf:["ytp-player-content","ytp-iv-player-content"]});g.m(this,this.U);g.Pw(this.player,this.U.element,4);this.U.hide();this.Y=new g.O({B:"div",nf:["ytp-iv-video-content"]});g.m(this,this.Y);B=this.createElement({B:"div",G:"video-annotations"});
B.appendChild(this.WD);this.Y.element.appendChild(B);this.dJ()&&this.load();var T=this.createElement({B:"style"});(g.fr("HEAD")[0]||document.body).appendChild(T);this.addOnDisposeCallback(function(){g.RK(T)});
if(B=T.sheet)B.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),B.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),B.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),B.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),B.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),B.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),B.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),B.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),B.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),B.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},ieg=function(B){B=B.createElement({B:"div",
nf:["annotation","annotation-type-custom"]});g.KF(B,!1);return B},c9h=function(B,z){z=!z.isCued()&&!g.X(z,1024);
B.U.kW(z);B.Y.kW(z)},Lbp=function(B,z,T){B.J=!0;
B.V=g.yH(z,T)},C$p=function(B,z){for(var T={},R=g.d(z.attributes),h=R.next();!h.done;h=R.next())h=h.value,T[h.name]=h.nodeValue;
for(R=0;R<z.childNodes.length;R++)if(h=z.childNodes[R],g.zU(h)&&h.nodeType==1){if(T[h.tagName])var W=T[h.tagName];else if(h.tagName==="data"){h.childNodes.length>0&&(W=h.childNodes[0].nodeValue,T[h.tagName]=typeof W==="string"?W.trim():W);continue}else W=[],T[h.tagName]=W;h&&h.tagName==="TEXT"?h.childNodes.length===1&&h.childNodes[0].nodeType===3?W.push(h.childNodes[0].nodeValue):W.push(""):h&&W.push(C$p(B,h))}return T},I0c=function(B){var z=B.player.getVideoData();
if(z.cD){var T=B.player.K().lO.get(z.videoId);if(T){var R={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(h,W,b){h=B.loadNumber;W=z.videoId;B.loaded&&B.loadNumber===h&&B.player.getVideoData().videoId===W&&(b=g.oc(b)&&b.responseXML?b.responseXML:null)&&r9K(B,b)}};
g.Rh()&&(R.onFinish=oWP(B,R.onFinish));R.postParams={ic_only:"1"};FbU(R,T);B.J=!0;g.yH(z.cD,R)}}},FbU=function(B,z){B.method="POST";
B.postParams=B.postParams||{};z.B6&&(B.postParams.ic_coll=z.B6);z.sZ&&(B.postParams.ic_xml=z.sZ);z.S9&&(B.postParams.ic_track=z.S9)},G0q=function(B){var z=new g.O({B:"div"});
g.KF(z.element,!1);var T=new DJp(B.player,z.element,bk(B));g.m(T,z);z.Vu(B.U.element);T.Vw();return T},A9K=function(B,z){var T,R;
if(z=(T=z.getWatchNextResponse())==null?void 0:(R=T.cards)==null?void 0:R.cardCollectionRenderer)B.TZ=!0,d1P(B,z),z.headerText&&B.R_&&(T=g.aU(z.headerText),B.R_.setAttribute("title",T))},bk=function(B){if(!B.N){var z=new TYI(B);
g.m(B,z);var T=new g.FM(B);g.m(B,T);B.N=new z5P(z,T,B.player.K(),B.player.getVideoData(),B.logger,B.player,B.RQ)}return B.N},r9K=function(B,z){var T=!1,R=z.getElementsByTagName("annotations");
if(R&&!(R.length<1)&&(R=R[0].getAttribute("itct"))){var h=g.gd();if(h){var W=g.yl();W&&g.BP(g.XP)(void 0,h,W,[g.Vl(R)])}}z=z.getElementsByTagName("annotation");for(R=0;R<z.length;R++){W=C$p(B,z[R]);h=null;try{if(W){var b=W.id,l=/.+/;var w=typeof b==="string"&&l!=null&&b!=null&&b.match(l)?b:"";var q=uE(W.type,a0p),c=uE(W.style,U1g),L=Itg(W.data),C=L.length!==0?JSON.parse(L):{};var r=W.action;W=MV5;if(r==null)var F=null;else if(g.B7(r)){l=[];for(var A=g.d(r),a=A.next();!a.done;a=A.next()){var V=W(a.value);
V&&l.push(V)}F=l}else{var M=W(r);F=M?[M]:[]}h=w&&q?new VV5(w,q,c,F,C):null}else h=null}catch(TP){}if(h)if(h.type==="branding"||h.type==="promotion"){W=B;l=h;var x=ieg(W),v=null;switch(l.type){case "branding":if(W.player.K().pF)break;W.U.element.appendChild(x);v=new ht(x,bk(W),l);break;case "promotion":g.Pw(W.player,x,4),v=new Tq7(x,bk(W),l)}v&&v.Vw();if(W=v)g.m(B,W),B.X[h.id]=W}else if(h.type==="card"||h.type==="drawer"){B.T||(B.T=G0q(B),g.m(B,B.T));if(h.type==="card"){x=B.T;var n=(T=h)&&T.data&&
T.data.card_type;h=T.data;if(n)switch(W=h.tracking||{},W={VP:W.impression,click:W.click,close:W.close,xx:W.teaser_impression,A2:W.teaser_click},l=h.tracking_params||{},v=null,n){case "collaborator":T={id:T.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,Bv:W,Ys:l.card?g.Vl(l.card):null,hY:l.teaser?g.Vl(l.teaser):null,Ef:l.icon?g.Vl(l.icon):
null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,profileImageUrl:h.image_url,title:h.title,metaInfo:h.meta_info,url:f_({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null};SO(x,T);break;case "playlist":T={id:T.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,Bv:W,
Ys:l.card?g.Vl(l.card):null,hY:l.teaser?g.Vl(l.teaser):null,Ef:l.icon?g.Vl(l.icon):null,Jp:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:f_({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null};SO(x,T);break;case "productListing":h.signin_url&&(v=f_({target:"current",value:h.signin_url}));n=[];for(var Z=h.offers||[],N=0;N<Z.length;N++)n.push(new $JI(g.IA(Z[N].merchant),
g.IA(Z[N].price)));T={id:T.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,Bv:W,Ys:l.card?g.Vl(l.card):null,hY:l.teaser?g.Vl(l.teaser):null,Ef:l.icon?g.Vl(l.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,u5:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?
h.custom_message:null,url:f_({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),DdJ:v,VPI:h.signin_title?h.signin_title:void 0,XZO:h.signin_message?h.signin_message:void 0,offers:n,onClickCommand:null};SO(x,T);break;case "simple":T={id:T.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,Bv:W,Ys:l.card?g.Vl(l.card):
null,hY:l.teaser?g.Vl(l.teaser):null,Ef:l.icon?g.Vl(l.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,u5:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:f_({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null};SO(x,T);break;case "video":T={id:T.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,
startMs:h.start_ms,autoOpen:h.auto_open||!1,sessionData:h.session_data||{},sponsored:h.sponsored||!1,Bv:W,Ys:l.card?g.Vl(l.card):null,hY:l.teaser?g.Vl(l.teaser):null,Ef:l.icon?g.Vl(l.icon):null,Jp:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:f_({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),onClickCommand:null},SO(x,T)}}else ksg(B.T,h);T=!0}}T&&
(V8(B.player),B.ze())},d1P=function(B,z){var T=!1;
B.T||(B.T=G0q(B),g.m(B,B.T));for(var R=g.d(z.cards||[]),h=R.next();!h.done;h=R.next())h=h.value,h.cardRenderer&&(Kuq(B.T,h.cardRenderer),T=!0);if(T){var W;(W=B.player.getVideoData())!=null&&g.pt(W)||(T=B.T,R=z.headerText?g.aU(z.headerText):"",g.Wt(T.U0,R),T.J&&T.J.setAttribute("title",R),T.context.videoData.eventId&&(T.eventId=T.context.videoData.eventId),T.XE=z.trackingParams?g.Vl(z.trackingParams):null,T.L=z.closeButton.infoCardIconRenderer.trackingParams?g.Vl(z.closeButton.infoCardIconRenderer.trackingParams):
null,T.Ef=z.icon.infoCardIconRenderer.trackingParams?g.Vl(z.icon.infoCardIconRenderer.trackingParams):null,B.ze());V8(B.player)}},MKq=function(B,z,T,R,h){if(!B.player.K().pF){var W=[];
z.navigationEndpoint&&g.u(z.navigationEndpoint,g.UR)&&g.u(z.navigationEndpoint,g.UR).browseId&&W.push(new AzK("openUrl","click",new Gsc("/channel/"+g.u(z.navigationEndpoint,g.UR).browseId,"new",!0,!0)));var b=z.watermark.thumbnails[0];R={channel_name:z.channelName,end_ms:z.endTimeMs,image_height:b.height,image_type:1,image_url:b.url,image_width:b.width,is_mobile:!1,session_data:{annotation_id:T,ei:h,feature:"iv",itct:z.trackingParams,src_vid:R},start_ms:z.startTimeMs};if(z.subscribeButton&&g.u(z.subscribeButton,
g.Mp)){R.channel_id=g.u(z.subscribeButton,g.Mp).channelId;var l;z=g.u(z.subscribeButton,g.Mp);b=h=null;z.subscribed?(z.subscriberCountWithUnsubscribeText&&(h=g.aU(z.subscriberCountWithUnsubscribeText)),z.subscriberCountText&&(b=g.aU(z.subscriberCountText))):(z.subscriberCountText&&(h=g.aU(z.subscriberCountText)),z.subscriberCountWithSubscribeText&&(b=g.aU(z.subscriberCountWithSubscribeText)));var w,q=((w=g.u((l=z.signInEndpoint)==null?void 0:l.commandMetadata,g.Gw))==null?void 0:w.url)||"";l={subscribeText:g.aU(z.unsubscribedButtonText),
subscribeCount:h||"",unsubscribeText:g.aU(z.subscribedButtonText),unsubscribeCount:b||"",enabled:z.enabled||!1,classic:!1,subscribed:z.subscribed||!1,feature:"iv",signInUrl:q};R.standalone_subscribe_button_data=l}W=new VV5(T,"branding","branding",W,R);l=ieg(B);B.U.element.appendChild(l);W=new ht(l,bk(B),W);W.Vw();g.m(W,W);B.X[T]=W}},oWP=function(B,z){return function(){var T=g.K5.apply(0,arguments);
B.xd()||B.UE.push(g.fi.u0(function(){z.apply(null,g.Q(T))}))}},VKF=function(B){return B==="annotation-editor"||B==="live-dashboard"};
g.M2.prototype.Mb=g.bd(45,function(B,z){var T=g.PH(this.bK());T&&T.Mb(B,z)});
var y8={},gD=null;g.qg(p_,g.C2);g.I=p_.prototype;g.I.getDuration=function(){return this.duration};
g.I.play=function(B){if(B||this.T==0)this.progress=0,this.coords=this.U;else if(this.isPlaying())return!1;Ja(this);this.startTime=B=g.YP();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.W=this.startTime;this.progress||this.dQ();this.NV("play");this.isPaused()&&this.NV("resume");this.T=1;var z=g.RR(this);z in y8||(y8[z]=this);ZFs();e7U(this,B);return!0};
g.I.stop=function(B){Ja(this);this.T=0;B&&(this.progress=1);sKI(this,this.progress);this.onStop();this.lr()};
g.I.pause=function(){this.isPlaying()&&(Ja(this),this.T=-1,this.NV("pause"))};
g.I.gF=function(){this.T==0||this.stop(!1);this.NV("destroy");p_.gD.gF.call(this)};
g.I.destroy=function(){this.dispose()};
g.I.qe=function(){this.NV("animate")};
g.I.NV=function(B){this.dispatchEvent(new E6I(B,this))};
g.qg(E6I,g.s3);g.qg($4,p_);$4.prototype.Y=function(){};
$4.prototype.qe=function(){this.Y();$4.gD.qe.call(this)};
$4.prototype.lr=function(){this.Y();$4.gD.lr.call(this)};
$4.prototype.dQ=function(){this.Y();$4.gD.dQ.call(this)};
g.qg(S9U,$4);S9U.prototype.Y=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.G(TYI,g.K);g.I=TYI.prototype;g.I.listen=function(B,z,T,R){T=(0,g.W7)(T,R||this.U);B=g.M4(B,z,T);this.T.push(B);return B};
g.I.Hh=function(B,z,T,R){T=(0,g.W7)(T,R||this.U);B=jKF(B,z,T);this.T.push(B);return B};
g.I.V2=function(B){g.VO(B);g.GU(this.T,B)};
g.I.removeAll=function(){g.VO(this.T);this.T.length=0};
g.I.gF=function(){this.removeAll();g.K.prototype.gF.call(this)};g.G(Wu7,g.I$);g.I=Wu7.prototype;g.I.load=function(){g.I$.prototype.load.call(this);if(!vv(this)){var B=g.ULr(this.player.getVideoData());B?(B=hup(B,b9P(this)),DK(this,B,!1)):Y57(this)}};
g.I.unload=function(){DK(this,null);this.W&&(this.W.abort(),this.W=null);g.I$.prototype.unload.call(this)};
g.I.vH=function(B,z){return vv(this)?B==="loadCustomEndscreenRenderer"?(B=hup(z,"new"),DK(this,B),!0):null:null};
g.I.getOptions=function(){return vv(this)?["loadCustomEndscreenRenderer"]:[]};
g.I.ox=function(){if(this.endscreen&&this.endscreen.elements){var B=this.player.getVideoContentRect();if(B&&B.width!==0&&B.height!==0){var z=this.player.getPlayerSize();if(z&&z.width!==0&&z.height!==0){var T=B.width/B.height;var R=0;for(var h=-1,W=0;W<QFp.length;W++){var b=Math.abs(z.width-QFp[W]);if(h===-1||R>=b)h=W,R=b}R=y9s[h];this.Y&&g.Ml(this.Y.element,"outline-width",Math.max(z.width,z.height)+"px");for(z=0;z<this.endscreen.elements.length;++z)if(W=this.endscreen.elements[z].id,h=this.U[W],
b=this.X[W],h&&b){var l=b.width*T/b.aspectRatio,w=Math.round(b.width*B.width);W=Math.round(l*B.height);var q=B.left+Math.round(b.left*B.width),c=B.top+Math.round(b.top*B.height);g.vt(h.element,w,W);g.pF(h.element,q,c);g.ci(h.element,gWs);w>256||W>256?g.ww(h.element,"ytp-ce-large-round"):w>96||W>96?g.ww(h.element,"ytp-ce-medium-round"):g.ww(h.element,"ytp-ce-small-round");g.ci(h.element,J9U);w=b.left+b.width/2;b=b.top+l/2;g.ww(h.element,w<=.5&&b<=.5?"ytp-ce-top-left-quad":w>.5&&b<=.5?"ytp-ce-top-right-quad":
w<=.5&&b>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.ci(h.element,y9s);g.ww(h.element,R);(h=g.Nu(document,"div","ytp-ce-expanding-overlay-body",h.element)[0])&&g.Ml(h,"height",W+"px")}}}}};
g.I.onCueRangeEnter=function(B){if(this.endscreen)if(B.getId()==="ytp-ce-in-endscreen")n_(this,this.endscreen.impressionUrls),(B=g.gd())&&this.endscreen.visualElement&&g.lU(B,this.endscreen.visualElement),this.T&&(g.ww(this.T,"ytp-ce-element-show"),this.T.removeAttribute("aria-hidden"),this.player.B7()?g.ww(this.T,"ytp-ce-hide-button-lower"):g.iH(this.T,"ytp-ce-hide-button-lower"));else{B=B.getId().substring(15);var z=this.U[B],T=this.X[B];g.ww(z.element,"ytp-ce-element-show");z.element.removeAttribute("aria-hidden");
z=this.player.getRootNode();g.ww(z,"ytp-ce-shown");n_(this,T.impressionUrls);(z=g.gd())&&g.lU(z,T.visualElement);this.player.K().J&&this.player.uO("endscreenelementshown",B)}};
g.I.onCueRangeExit=function(B){if(B.getId()==="ytp-ce-in-endscreen")this.T&&(g.iH(this.T,"ytp-ce-element-show"),this.T.setAttribute("aria-hidden","true"));else{B=B.getId().substring(15);var z=this.U[B];g.iH(z.element,"ytp-ce-element-show");z.element.setAttribute("aria-hidden","true");z=this.player.getRootNode();g.iH(z,"ytp-ce-shown");this.player.K().J&&this.player.uO("endscreenelementhidden",B)}};
g.I.utd=function(B){var z=this;B.target===window&&(new g.Si(function(){for(var T=g.d(Object.values(z.U)),R=T.next();!R.done;R=T.next())g.ci(R.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.I.kW=function(B){for(var z=g.d(Object.values(this.U)),T=z.next();!T.done;T=z.next())T=T.value,B?T.element.setAttribute("hidden",""):T.element.removeAttribute("hidden")};
g.I.Q1E=function(B){this.T&&this.player.getRootNode().removeChild(this.T);B&&(g.ww(B,"ytp-ce-hide-button-container"),this.T=B,g.Pw(this.player,this.T,4))};
var QFp=[346,426,470,506,570,640,853,1280,1920],y9s="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),J9U=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],gWs=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var dJc={jqD:"current",eRD:"new"};var ats={CLOSE:"close",kGE:"openUrl",SUBSCRIBE:"subscribe"},UJg={AuJ:"click",CLOSE:"close",X7J:"hidden",K2I:"rollOut",p3m:"rollOver",knF:"shown"};VV5.prototype.Pu=function(){var B=Qr5(this,function(z){return z.type==="openUrl"&&z.url!=null});
return B?B.url:null};
var U1g={Tsf:"anchored",pW:"branding",CHANNEL:"channel",B0u:"cta",nYK:"highlightText",TvO:"label",PLAYLIST:"playlist",POPUP:"popup",OtG:"speech",SUBSCRIBE:"subscribe",nBK:"title",VIDEO:"video",vBd:"website"},a0p={pW:"branding",MwE:"card",qXJ:"drawer",Djd:"highlight",xKJ:"marker",lXF:"promotion",TEXT:"text",tbD:"widget"};g.G(jO,g.K);g.I=jO.prototype;g.I.addCueRange=function(B,z,T,R,h){B=new g.Wj(B,z,{id:T,namespace:"annotations_module"});R&&this.Kf.set(B,R);h&&this.sE.set(B,h);this.context.j.A$([B],1)};
g.I.Vw=function(){this.context.U.subscribe("resize",this.Ye,this)};
g.I.jk=function(){return this.element};
g.I.yq=function(B,z,T,R,h,W){if(this.EE)return!1;W&&(W.stopPropagation(),W.preventDefault());this.navigate(B,T,R,h);return!1};
g.I.show=function(){};
g.I.hide=function(){};
g.I.destroy=function(){g.RK(this.jk())};
g.I.Ye=function(){};
g.I.navigate=function(B,z,T,R){var h=this,W=Hv(B);if(W){var b=xJU(W,B.target),l=function(){B.T&&h.context.j.pauseVideo();var w=h.context.videoData.Jj||!1,q=g.bA(W||"");w&&q&&(q.v||q.list)?h.context.j.Dw(q.v,z,q.list,!1):g.Zw(W||"",b==="current"?"_top":void 0,z)};
b==="new"&&(l(),l=null);WC(this.context.logger,T,l,R);PTW(W)||(T=g.gd(),R=z.itct,T&&R&&g.iU(T,g.Vl(R)))}};
g.I.gF=function(){this.Kf.clear();this.sE.clear();g.K.prototype.gF.call(this)};
g.I.createElement=function(B){B=new g.O(B);g.m(this,B);return B.element};g.G(DJp,jO);g.I=DJp.prototype;g.I.MK=function(){this.UE&&SO(this,this.UE)};
g.I.isAvailable=function(){var B;if(B=!!this.cards.length)(B=this.j.getRootNode())?(B=g.Dk(B),B=173<B.width&&173<B.height):B=!1;return B};
g.I.Ye=function(){var B=this.isAvailable();g.KF(this.jk(),B);g.L2(this.context.j.getRootNode(),g.ZR.IV_DRAWER_ENABLED,B);V8(this.j)};
g.I.destroy=function(){this.j.Mb(!1);try{this.j.getRootNode().removeChild(this.W)}catch(B){}g.l_(this.TZ);g.$K(this.cD);this.IK&&this.IK.dispose();this.V&&this.V.dispose();jO.prototype.destroy.call(this)};
g.I.eA=function(){var B=this;this.context.T.listen(g.t2("iv-drawer-close-button",this.W),"click",this.KP,this);this.context.T.listen(this.U,"touchend",function(){B.RK.start()});
this.context.T.listen(this.U,"scroll",this.jr,this);this.context.U.subscribe("onHideControls",function(){B.lO=!0});
this.context.U.subscribe("onShowControls",function(){B.lO=!1});
this.context.U.subscribe("onVideoAreaChange",function(){B.lO=g.lH(B.j.getRootNode(),"ytp-autohide")});
this.TZ.push(g.Y2("iv-button-shown",this.XDG,this));this.TZ.push(g.Y2("iv-button-hidden",this.Rmu,this));ft7(this)};
g.I.findLastIndex=function(B){if(this.cards.length===0)return 0;var z=g.oR(this.cards,function(T){return B.Hd.startMs>T.Hd.startMs||B.Hd.startMs===T.Hd.startMs&&B.Hd.timestamp>=T.Hd.timestamp?!0:!1});
return z===-1?0:z+1};
g.I.KP=function(){if(this.Y){WC(this.context.logger,TA(this).Bv.close);var B=g.gd();B&&this.L&&g.iU(B,this.L);sb(this)}};
g.I.jr=function(){g.L2(this.W,"iv-drawer-scrolled",this.U.scrollTop>0)};
g.I.XDG=function(){var B=g.gd(),z=TA(this);z=z?z.Ef:this.Ef;B&&z&&g.w2(B,[z])};
g.I.Rmu=function(){var B=g.gd(),z=TA(this);z=z?z.Ef:this.Ef;B&&z&&g.qI(B,[z])};
g.I.YE=function(){var B=TA(this);WC(this.context.logger,B.Bv.xx);var z=g.gd();if(z&&B)if(this.j.D("web_infocards_teaser_show_logging_fix")){var T=[];B.hY&&T.push(B.hY);B.Ef&&T.push(B.Ef);T.length>0&&g.w2(z,T)}else g.w2(z,[B.hY,B.Ef])};
g.I.VIu=function(){var B=g.gd(),z=TA(this);B&&z&&g.qI(B,[z.hY])};
g.I.OY=function(B){var z=TA(this),T=g.gd();this.T?B?(B=this.context.logger,WC(B,z.Bv.A2),B.j.sendVideoStatsEngageEvent(4,void 0),T&&z.hY&&g.iU(T,z.hY)):(B=this.context.logger,WC(B,z.Bv.A2),B.j.sendVideoStatsEngageEvent(4,void 0),T&&z.Ef&&g.iU(T,z.Ef)):(B=this.context.logger,WC(B,z.Bv.A2),B.j.sendVideoStatsEngageEvent(4,void 0),T&&this.Ef&&g.iU(T,this.Ef))};g.G(Rk,jO);Rk.prototype.Vw=function(){jO.prototype.Vw.call(this);euP(this)};
Rk.prototype.show=function(){jO.prototype.show.call(this);var B=g.gd(),z=this.annotation.data;B&&z&&(z=z.session_data)&&g.w2(B,[g.Vl(z.itct)])};
Rk.prototype.hide=function(){jO.prototype.hide.call(this);var B=g.gd(),z=this.annotation.data;B&&z&&(z=z.session_data)&&g.qI(B,[g.Vl(z.itct)])};g.G(ht,Rk);
ht.prototype.show=function(){if(!this.isActive){Rk.prototype.show.call(this);if(!this.L){g.ww(this.jk(),"iv-branding");var B=this.annotation.data;this.U=this.createElement({B:"img",nf:["branding-img","iv-click-target"],C:{"aria-label":"Channel watermark",src:B.image_url,width:B.image_width,height:B.image_height}});g.KF(this.U,!1);var z=this.createElement({B:"button",nf:["branding-img-container","ytp-button"]});z.appendChild(this.U);this.jk().appendChild(z);var T=this.annotation.Pu();T&&Xv(this,z,
T,this.annotation.id,B.session_data);this.context.j.D("disable_branding_context")||BqF(this,B);this.L=!0}g.KF(this.jk(),!0);this.isActive=!0;if(this.U){try{srP(this,this.U)}catch(R){}g.ww(this.context.j.getRootNode(),"ytp-branding-shown");this.context.j.getRootNode().style.setProperty("--branding-image-width",this.U.getAttribute("width")+"px")}}};
ht.prototype.hide=function(){this.isActive&&(Rk.prototype.hide.call(this),g.KF(this.jk(),!1),this.isActive=!1,g.iH(this.context.j.getRootNode(),"ytp-branding-shown"))};
ht.prototype.destroy=function(){this.T&&(this.T.dispose(),this.T=null);g.iH(this.context.j.getRootNode(),"ytp-branding-shown");Rk.prototype.destroy.call(this)};g.G(Tq7,Rk);g.I=Tq7.prototype;g.I.show=function(){this.isActive||(Rk.prototype.show.call(this),this.N||(h5q(this),this.N=!0),g.KF(this.jk(),!0),g.mW(function(){g.iH(this.jk(),"iv-promo-inactive")},100,this),this.jk().removeAttribute("aria-hidden"),this.isActive=!0,l05(this),Wbh(this),beF(this,this.X))};
g.I.hide=function(){this.isActive&&(g.ww(this.jk(),"iv-promo-inactive"),this.isActive=!1,this.jk().setAttribute("aria-hidden","true"))};
g.I.yq=function(B,z,T,R,h,W){return this.isCollapsed?!1:Rk.prototype.yq.call(this,B,z,T,R,h,W)};
g.I.vz=function(B){this.J=!0;R5q(this,500,B)};
g.I.hc=function(){this.J=!1;YMW(this)};
g.I.Ac=function(B){B.stopPropagation();this.hide()};
g.I.Et=function(B){B.stopPropagation();l05(this);this.isCollapsed=!0;g.ww(this.jk(),"iv-promo-collapsed-no-delay");this.V.start()};
g.I.destroy=function(){this.V.dispose();Rk.prototype.destroy.call(this)};g.G(qMh,g.I$);g.I=qMh.prototype;g.I.vH=function(B,z){if(!VKF(this.player.K().playerStyle))return null;switch(B){case "loadCustomAnnotationsXml":return(B=g.ZQ(z))&&r9K(this,B),!0;case "removeCustomAnnotationById":return z&&this.T&&(nnF(this.T,z),V8(this.player)),!0}return null};
g.I.getOptions=function(){return VKF(this.player.K().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.I.dJ=function(){var B=this.player.K(),z=this.player.getVideoData(),T=B.annotationsLoadPolicy||z.annotationsLoadPolicy;return g.Zr(z)||this.player.isMutedByEmbedsMutedAutoplay()?!1:T===1&&!z.Zt||B.lO.get(z.videoId)||g.$h(z)||g.Px(z)?!0:!1};
g.I.ze=function(){if(this.Y){var B=this.player.NG().getVideoContentRect(!0);g.vt(this.Y.element,B.width,B.height);g.pF(this.Y.element,B.left,B.top)}if(this.T){var z=this.player.ZO();B=this.T;z=z.width;g.L2(B.W,"iv-drawer-small",z<=426);g.L2(B.W,"iv-drawer-big",z>=1280)}};
g.I.gW=function(B){c9h(this,B.state);g.X(B.state,2)&&(this.B7()&&this.TX()&&this.player.getPresentingPlayerType()!==2&&this.KG(!1),this.Mb(!1))};
g.I.load=function(){function B(b){var l=z.loadNumber;z.V=null;z.loaded&&z.loadNumber===l&&z.player.getVideoData().videoId===R&&(b=g.oc(b)&&b.responseXML?b.responseXML:null)&&(r9K(z,b),g.ww(z.player.getRootNode(),"iv-module-loaded"))}
var z=this;g.I$.prototype.load.call(this);c9h(this,this.player.getPlayerStateObject());this.loadNumber++;var T=this.player.getVideoData(),R=T.videoId;g.Rh()&&(B=oWP(this,B));var h={format:"XML",onFinish:B,onError:function(){z.V=null},
urlParams:{}};T.isPharma&&(h.urlParams.pharma="1");h.method="POST";h.withCredentials=!0;var W=this.player.K().lO.get(R);W&&FbU(h,W);W=W&&(W.sZ||W.B6);if(!T.c_||W)T.cD?Lbp(this,T.cD,h):(this.L=function(){if(!z.J)z.onVideoDataChange(h);var b=z.player.getVideoData();(b==null?0:g.pt(b))&&!z.TZ&&A9K(z,b)},this.player.addEventListener("videodatachange",this.L));
g.Pw(this.player,this.Y.element,4);this.ze();(W=g.$h(T))&&d1P(this,W);(W=g.Px(T))&&W.featuredChannel&&MKq(this,W.featuredChannel,W.annotationId||"branding",T.videoId||null,T.eventId||null);this.R_=g.t2("ytp-cards-button",this.player.getRootNode());g.pt(T)&&A9K(this,T)};
g.I.onVideoDataChange=function(B){var z=this.player.getVideoData();z.cD&&Lbp(this,z.cD,B)};
g.I.unload=function(){this.player.I7("annotations_module");for(var B=g.d(Object.keys(this.X)),z=B.next();!z.done;z=B.next())this.X[z.value].destroy();this.N=null;this.T&&(this.T.destroy(),this.T=null,V8(this.player));this.J=!1;this.V&&(this.V.abort(),this.V=null);this.TZ=!1;this.X={};this.U.hide();g.I$.prototype.unload.call(this);this.Y.detach();this.L&&(this.player.removeEventListener("videodatachange",this.L),this.L=null)};
g.I.Pe=function(B){B===this.player.getVideoData().videoId&&(this.loaded?I0c(this):this.load())};
g.I.B7=function(){var B;return((B=this.T)==null?void 0:B.isAvailable())||this.TZ};
g.I.TX=function(){return!!this.T&&this.T.Y};
g.I.KG=function(B,z,T){z=z===void 0?!1:z;this.B7();this.T&&(B?T?eO(this.T,T,z):eO(this.T,"YOUTUBE_DRAWER_AUTO_OPEN",z):sb(this.T))};
g.I.Mb=function(B,z){this.player.publish(B?"cardsteasershow":"cardsteaserhide",z)};
g.I.gF=function(){this.player.K().lO.unsubscribe("vast_info_card_add",this.Pe,this);g.iH(this.player.getRootNode(),g.ZR.IV_DRAWER_OPEN);for(var B=this.UE,z=g.fi,T=0,R=B.length;T<R;T++)z.Xg(B[T]);this.UE.length=0;g.I$.prototype.gF.call(this)};
g.I.createElement=function(B){B=new g.O(B);g.m(this,B);return B.element};g.Fj("annotations_module",qMh);g.Fj("creatorendscreen",Wu7);})(_yt_player);
